/*
 * ColumnHomogeneityChartPanel.java
 *
 * Created on October 1, 2008, 9:13 PM
 */
package edu.unam.iimas.glocsa.glocser.glocsadetails;

import edu.unam.iimas.alignment.glocsa.core.GlocsaRating;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYBarDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author  xaltonalli
 */
public class ColumnHomogeneityChartPanel extends javax.swing.JPanel {
    
    private GlocsaRating glocsaRating = null;

    private JFreeChart chart = null;
    
    public void setGlocsaRating(GlocsaRating glocsaRating) {
        this.glocsaRating = glocsaRating;
    }
    
    public GlocsaRating getGlocsaRating() {
        return glocsaRating;
    }
    
    /** Creates new form ColumnHomogeneityChartPanel */
    public ColumnHomogeneityChartPanel() {
        initComponents();

        //createChart();
        
        
    }

    public void createChart() {

        double[] columnValues = null;
        if (glocsaRating != null) {
            columnValues = glocsaRating.getColumnValues();
        } else {
            columnValues = new double[1];
        }
        
        XYSeriesCollection xyDataSet = new XYSeriesCollection();
        XYSeries xySeries = new XYSeries("CV");

        for (int i = 0; i < columnValues.length; i++) {
            xySeries.add((double) i, columnValues[i]);
        }

        xyDataSet.addSeries(xySeries);
        XYBarDataset xyBarDataSet = new XYBarDataset(xyDataSet, 1.0);


        chart = ChartFactory.createXYBarChart(
                "Column Homogeneity",
                "sequence position",
                false,
                "value",
                xyBarDataSet,
                PlotOrientation.VERTICAL,
                false, // include legend
                true,
                false);

        XYPlot plot = chart.getXYPlot();
        ValueAxis domainAxis = plot.getDomainAxis();
        domainAxis.setRange(0, columnValues.length - 1);
        
        ///////// GUI

        ChartPanel chartPanel = new ChartPanel(chart);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 380, Short.MAX_VALUE));
        panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 280, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
