/*
 * GlocsaDetailsFrame.java
 *
 * Created on September 29, 2008, 10:27 PM
 */

package edu.unam.iimas.glocsa.glocser.glocsadetails;

import edu.unam.iimas.alignment.Alignment;
import edu.unam.iimas.alignment.DynamicAlignment;
import edu.unam.iimas.alignment.glocsa.core.EventCount;
import edu.unam.iimas.alignment.glocsa.core.GlocsaRating;
import edu.unam.iimas.alignment.glocsa.core.SGCMatrix;
import java.io.File;

/**
 *
 * @author  xaltonalli
 */
public class GlocsaDetailsFrame extends javax.swing.JFrame {
    
    private DynamicAlignment openDynamicAlignment;
    private GlocsaRating glocsaRating;
    private EventCount eventCount;
    private File openAlignmentFile;

    /** Creates new form GlocsaDetailsFrame */
    public GlocsaDetailsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        glocsaRatingPanel = new edu.unam.iimas.glocsa.glocser.glocsadetails.GlocsaRatingPanel();
        columnHomogeneityChartPanel = new edu.unam.iimas.glocsa.glocser.glocsadetails.ColumnHomogeneityChartPanel();
        columnDiversityChartPanel = new edu.unam.iimas.glocsa.glocser.glocsadetails.ColumnDiversityChartPanel();
        gapSizeChartTablePanel = new edu.unam.iimas.glocsa.glocser.glocsadetails.GapSizeChartTablePanel();
        sCGMatrixPanel = new edu.unam.iimas.glocsa.glocser.glocsadetails.SCGMatrixPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GLOCSA Details");
        setIconImages(null);

        jTabbedPane.addTab("GLOCSA Rating", glocsaRatingPanel);
        jTabbedPane.addTab("CH Chart", columnHomogeneityChartPanel);

        javax.swing.GroupLayout columnDiversityChartPanelLayout = new javax.swing.GroupLayout(columnDiversityChartPanel);
        columnDiversityChartPanel.setLayout(columnDiversityChartPanelLayout);
        columnDiversityChartPanelLayout.setHorizontalGroup(
            columnDiversityChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        columnDiversityChartPanelLayout.setVerticalGroup(
            columnDiversityChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Diversity Chart", columnDiversityChartPanel);
        jTabbedPane.addTab("Gap Sizes Chart", gapSizeChartTablePanel);
        jTabbedPane.addTab("SCG Matrix", sCGMatrixPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlocsaDetailsFrame().setVisible(true);
            }
        });
    }
    
    public void createCharts() {
        if ( openDynamicAlignment != null && glocsaRating != null && eventCount != null && openAlignmentFile != null ) {
            columnDiversityChartPanel.createChart();
            columnHomogeneityChartPanel.createChart();
            gapSizeChartTablePanel.createChart();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.unam.iimas.glocsa.glocser.glocsadetails.ColumnDiversityChartPanel columnDiversityChartPanel;
    private edu.unam.iimas.glocsa.glocser.glocsadetails.ColumnHomogeneityChartPanel columnHomogeneityChartPanel;
    private edu.unam.iimas.glocsa.glocser.glocsadetails.GapSizeChartTablePanel gapSizeChartTablePanel;
    private edu.unam.iimas.glocsa.glocser.glocsadetails.GlocsaRatingPanel glocsaRatingPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private edu.unam.iimas.glocsa.glocser.glocsadetails.SCGMatrixPanel sCGMatrixPanel;
    // End of variables declaration//GEN-END:variables

    
    public void setOpenDynamicAlignment(DynamicAlignment openDynamicAlignment) {
        this.openDynamicAlignment = openDynamicAlignment;
        Alignment minimalAlignment = openDynamicAlignment.getMinimalAlignment();
        glocsaRatingPanel.setDynamicAlignment(openDynamicAlignment);
        columnDiversityChartPanel.setAlignment(minimalAlignment);
        gapSizeChartTablePanel.setAlignment(minimalAlignment);
        sCGMatrixPanel.setAlignment(minimalAlignment);
    }

    public void setGlocsaRating(GlocsaRating glocsaRating) {
        this.glocsaRating = glocsaRating;
        glocsaRatingPanel.setRating(glocsaRating);
        columnHomogeneityChartPanel.setGlocsaRating(glocsaRating);
    }

    public void setEventCount(EventCount eventCount) {
        this.eventCount = eventCount;
        glocsaRatingPanel.setEventCount(eventCount);
        columnDiversityChartPanel.setEventCount(eventCount);
        
    }

    public void setOpenAlignmentFile(File openAlignmentFile) {
        this.openAlignmentFile = openAlignmentFile;
        glocsaRatingPanel.setAlignmentFile(openAlignmentFile);
        sCGMatrixPanel.setOpenAlignmentFile(openAlignmentFile);
    }
    
}
